export const AUTH_ERRORS = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const

export type AuthErrorCode = (typeof AUTH_ERRORS)[keyof typeof AUTH_ERRORS]
